import Link from "next/link";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Schedule App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center m-10  ">
          <Link className="font-bold text-xl lg:text-4xl" href={"/"}>
            JADWAL IBADAH JEMAT RAYON VII
          </Link>
        </div>

        <div className="max-w-4xl mx-auto px-5">{children}</div>
      </body>
    </html>
  );
}
