import Link from "next/link";

import "./globals.css";
import { Inter } from "next/font/google";
import TopHeader from "./components/topheader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Schedule App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader />
        <div className="max-w-4xl mx-auto px-5">{children}</div>
      </body>
    </html>
  );
}
